spring:
  datasource: ## batch, task 용
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1
    username: sa
    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: none
#        format_sql: true